---
- name: Install Ansible AWX
  hosts: localhost
  gather_facts: true
  become: yes
  vars:
    ansible_user: vagrant # user to login with SSH, must have sudo rights
    lldap_base_url: 'ldap.lab.local' 
    awx__base_url: 'awx.lab.local'
    nautobot__base_url: 'cmdb.lab.local'
    gitea__base_url: 'git.lab.local'
  tasks:
    # Include vars from full install role
    - name: Include vars from role
      ansible.builtin.include_vars:
        file: ./roles/full_install_config/defaults/main.yml

    - name: Check if docker is installed
      ansible.builtin.include_role:
        name: bsmeding.docker

    - name: Check if nginx is installed
      ansible.builtin.include_role:
        name: bsmeding.nginx_docker      

    # - name: Check if LLDAP is installed
    #   include_role:
    #     name: bsmeding.lldap_docker

    - name: Check if nautobot is installed
      include_role:
        name: bsmeding.nautobot_docker

    # - name: Check if gitea is installed
    #   include_role:
    #     name: bsmeding.gitea_docker

    - name: Check if awx is installed
      ansible.builtin.include_role:
        name: bsmeding.awx_docker

    - name: Run ContainerLab install script
      ansible.builtin.shell: bash -c "$(curl -sL https://get.containerlab.dev)"
      become: true
      changed_when: false

    - name: Create containerlab directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/containerlab
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy local lab directory to destination
      ansible.builtin.copy:
        src: containerlabs/*
        dest: /home/{{ ansible_user }}/containerlab/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
